import { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'About ReadersOnTheSpectrum - AI-Powered Reading Support for Children',
  description: 'Learn how ReadersOnTheSpectrum uses artificial intelligence to create personalized reading comprehension worksheets for children on the spectrum and ADHD. Our mission is to make reading accessible and enjoyable for every child.',
  keywords: 'spectrum reading support, ADHD learning tools, AI education, reading comprehension, special needs, inclusive education',
}

export default function AboutPage() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 via-white to-purple-50">
      {/* Header */}
      <header className="bg-white shadow-sm">
        <div className="max-w-4xl mx-auto px-4 py-8">
          <Link href="/" className="text-blue-600 hover:text-blue-800 font-medium mb-4 inline-block">
            ← Back to Home
          </Link>
          <h1 className="text-4xl md:text-5xl font-bold text-gray-900 mb-4">
            About ReadersOnTheSpectrum
          </h1>
          <p className="text-xl text-gray-600">
            Empowering children on the spectrum and ADHD through AI-powered reading comprehension tools
          </p>
        </div>
      </header>

      {/* Main Content */}
      <main className="max-w-4xl mx-auto px-4 py-12">
        <article className="prose prose-lg max-w-none">
          <section className="mb-12">
            <h2 className="text-3xl font-bold text-gray-900 mb-6">✨ About ReadersOnTheSpectrum</h2>
            <p className="text-gray-700 leading-relaxed mb-6">
              As a parent of a child with autism, I've experienced firsthand how difficult it can be to find learning resources that truly meet our children's unique needs.
            </p>
            <p className="text-gray-700 leading-relaxed mb-6">
              I often asked myself—What if I could use my background in AI and software to build something that actually helps?
            </p>
            <p className="text-gray-700 leading-relaxed mb-6">
              That question led to the creation of ReadersOnTheSpectrum.
            </p>
            <p className="text-gray-700 leading-relaxed mb-6">
              What began as a tool to support my own child's reading journey quickly became something more. I realized that the worksheets generated by this tool—structured, personalized, and visually engaging—were making a real difference.
            </p>
            <p className="text-gray-700 leading-relaxed mb-6">
              I knew I couldn't keep this to myself. I wanted to share it with other parents, educators, and therapists who are walking a similar path.
            </p>
          </section>

          <section className="mb-12">
            <h2 className="text-3xl font-bold text-gray-900 mb-6">💡 What is ReadersOnTheSpectrum?</h2>
            <p className="text-gray-700 leading-relaxed mb-6">
              ReadersOnTheSpectrum is an AI-powered platform that creates custom reading comprehension worksheets specifically designed for children on the spectrum and those with ADHD.
            </p>
            <p className="text-gray-700 leading-relaxed mb-6">
              The system combines:
            </p>
            <ul className="text-gray-700 leading-relaxed mb-6 space-y-2">
              <li>🔹 Evidence-based educational strategies</li>
              <li>🔹 Personalized content tailored to each child's interests and reading level</li>
              <li>🔹 Visual, structured, and repetitive formats proven to support neurodivergent learners</li>
            </ul>
            <p className="text-gray-700 leading-relaxed mb-6">
              It's designed to be simple and accessible—whether you're a teacher, therapist, or parent without any special training.
            </p>
            <p className="text-gray-700 leading-relaxed mb-6">
              You can generate high-quality worksheets in seconds, track progress over time, and help children learn in a way that works for them.
            </p>
          </section>

          <section className="mb-12">
            <h2 className="text-3xl font-bold text-gray-900 mb-6">🌱 Our Hope</h2>
            <p className="text-gray-700 leading-relaxed mb-6">
              My hope is that ReadersOnTheSpectrum will be a meaningful companion for families like mine—removing guesswork, reducing stress, and bringing back joy into learning.
            </p>
            <p className="text-gray-700 leading-relaxed mb-6">
              If this tool brings even a little relief or progress to your child's journey, then it's all been worth it.
            </p>
          </section>

          <section className="bg-blue-50 p-8 rounded-lg">
            <h2 className="text-3xl font-bold text-gray-900 mb-6">Ready to Get Started?</h2>
            <p className="text-gray-700 leading-relaxed mb-6">
              Join thousands of families who are already using ReadersOnTheSpectrum to support their children's reading journey. Try our platform today and see the difference personalized learning can make.
            </p>
            <Link 
              href="/register"
              className="inline-flex items-center bg-gradient-to-r from-blue-500 to-purple-600 hover:from-blue-600 hover:to-purple-700 text-white px-8 py-3 rounded-lg font-semibold transition-all shadow-lg hover:shadow-xl"
            >
              Start Your Free Trial →
            </Link>
          </section>
        </article>
      </main>
    </div>
  )
}
